[bidding]
#bidder = models/gib40/bidding-1000000
#bidder = models/4gib40/bidding-2500000
#bidder = models/4gib40_96/bidding-4990000
bidder = models/bengen_96/bidding-4990000
# bidder = models/argine/bidding-530000
#info = models/4gib40_binfo/binfo-240000
# info = models/4gib40_64_binfo/binfo-990000
info = models/bengen_binfo/binfo-970000
# info = models/4gib40_64_binfo/binfo-90000
# info = models/gib40_binfo/binfo-500000
# info = models/argine_binfo/binfo-500000

[eval]
lead_single_dummy = models/lr3ddl_model/lr3-2000000

[peekplay]
# peekplay = models/peekddl/peekddl-370000
# peekplay = models/peekddl_tiny/peekddl-90000
# peekplay = models/peekddl_micro/peekddl-1000000
peekplay = models/peekddl_256/peekddl-3990000
#peekplay = models/peekddl_micro/peekddl-1000000
# peekplay = models/peekddl_big/peekddl-50000

[poseval]
poseval = models/poseval/poseval-1000000

[lead]
peekplay = models/peekplay/peekplay-430000
